# -*- coding: utf-8 -*-
"""recommender_boolean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BYgaUOmqvKoQGPTFec1FMIlrSyUWu-Ek
"""

import numpy as np
import pandas as pd
import json
import matplotlib.pyplot as plt
import pyparsing as pp

from google.colab import drive

drive.mount('/content/drive')

def load_json(filename):
  with open (filename, "r", encoding ="utf-8") as f:
    query = json.load(f)
    return query

query0 = load_json("/content/drive/MyDrive/Colab Notebooks/475/results/query0.json")
print(query0)

query1 = load_json("/content/drive/MyDrive/Colab Notebooks/475/results/query1.json")
print(query1)

query2 = load_json("/content/drive/MyDrive/Colab Notebooks/475/results/query2.json")
print(query2)

query3 = load_json("/content/drive/MyDrive/Colab Notebooks/475/results/query3.json")
print(query3)

query0["seed"]
query1["seed"]
query2["seed"]
query3["seed"]

query = query3

metadata_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/475/id_metadata.csv",  sep="\t")
info_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/475/id_information.csv",  sep="\t")
lang_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/475/id_lang.csv",  sep="\t")
genres_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/475/id_genres.csv",  sep="\t")
tags_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/475/id_tags.csv",  sep="\t")
dataframes = [metadata_df, info_df, lang_df, genres_df, tags_df]

metadata_df.head()

info_df.head()

lang_df.head()

genres_df.head()

tags_df.head()

search_df = pd.concat([metadata_df.set_index("id"), info_df.set_index("id"),
                       lang_df.set_index("id"), genres_df.set_index("id"), tags_df.set_index("id")], axis=1)
search_df = search_df.reset_index()

search_df.head()

print(search_df.shape)

for col in metadata_df.columns:
    print(f"{col} Max {np.max(np.array(metadata_df[col]))}")
    print(f"{col} Min {np.min(np.array(metadata_df[col]))}")

def get_song_id(song, info_df):
    # take selection and projection
    # of id_information to get seed
    # song id from given song title and artist name
    # filter for non empty attributes
    attributes = {k:v for k,v in song.items() if v}

    # get keys and values from filtered attributes
    # with keys selecting for columns
    # and values used for comparison
    cols = list(attributes.keys())
    vals = list(attributes.values())

    # then do selection and take projection of row "id"
    return info_df.loc[(info_df[cols] == vals).all(axis=1), "id"]

song_id = get_song_id(query0["seed"], info_df).item()
print(type(song_id))
print(song_id)

search_df = pd.concat([metadata_df.set_index("id"), info_df.set_index("id"),
                       lang_df.set_index("id"), genres_df.set_index("id"), tags_df.set_index("id")], axis=1)
search_df = search_df.reset_index()

def parse_expression(col, expr):

    # define boolean operators for filtering
    ops = ['>=', '<=', '>', '<']
    op = pp.one_of(ops)

    # define atom for parsing
    atom = (pp.Optional(op, default="==")) + (pp.Word(pp.nums) | pp.Word(pp.alphas)| pp.quoted_string)
    atom.set_parse_action(lambda toks: f"{col}"+"".join(toks))

    # define pattern
    # use lambda on extracted tokens to add parentheses to expressions
    # i.e year>=2018 & year <= 2025 || year==2005
    # will be returned as ((year>=2018 & year <= 2025)||(year==2005))
    # index on toks[0] as each tok is nested as [['release>=2018', '&', 'release<=2025']]
    pattern = pp.infix_notation(atom, [ ("&", 2, pp.OpAssoc.LEFT,lambda toks: f"({''.join(toks[0])})"),
                                    ("||", 2, pp.OpAssoc.LEFT,lambda toks: f"({''.join(toks[0])})")])

    # return parsed expression
    return pattern.parse_string(expr)[0]

def get_filtered_metadata(constraints, search_df):
    # genre -> id_genres
    # lang -> id_lang
    # artist, song, album_name -> id_information
    # release -> id_metadata

    # get non empty attributes
    inclusion = {k:v for k,v in constraints["include"].items() if v}
    exclusion = {k:v for k,v in constraints["exclude"].items() if v}


    mask = np.full(search_df.shape[0], True)
    for col, vals in inclusion.items():
        # handle genre case separately
        # as genres column contains list of values
        # to compare against
        if col == "genres":
            mask &= search_df["genres"].apply(lambda x: any(item.strip()
                                                in list(vals) for item in x.split(",")))
        else:
            # loop over all expressions for column
            # init query to be used for filtering
            expressions = []
            for expr in vals:
                # parse each expression
                expr = parse_expression(col, expr)
                expressions.append(expr)

            # join each expression together
            # via conjunction
            query = "|".join(expressions)
            # perform serach on database
            mask &= search_df.eval(query)


    for col, vals in exclusion.items():
        # handle genre case separately
        # as genres column contains list of values
        # to compare against
        if col == "genres":
            mask &= search_df["genres"].apply(lambda x: any(item.strip()
                                                in list(vals) for item in x.split(",")))
        else:
            expressions = []
            for expr in vals:
                expr = parse_expression(col, expr)
                expressions.append(expr)

            query = "|".join(expressions)

            mask &= ~search_df.eval(query)

    # return result of applying mask
    return search_df[mask]

search_df = get_filtered_metadata(query["constraints"],search_df)

search_df.shape

def get_feature_vector(song_id, metadata_df, features):
    # given id for selected song
    # retreive assoicated metadata
    # from id_metadata.csv
    return metadata_df.loc[metadata_df["id"] == song_id, features.keys()].to_numpy()[0]

f_v = get_feature_vector(song_id, metadata_df, query["features"])
f_v

def knn(f_v,search_df,features,k):
    # compute norm between feature vector
    # and all elements in dataframe
    # using specified parameters to compare against
    weights = np.array(list(features.values()))
    norms = np.linalg.norm(np.sqrt(weights) * (search_df[list(features.keys())].to_numpy() - f_v), axis=1)
    # get sorted knn indices
    return np.argsort(norms)[:k]

k_indices = knn(f_v, search_df, query["features"],query["k"])
print(k_indices)

def get_knn_ids(k_indices, search_df):
    return search_df.iloc[k_indices]["id"]

k_ids = get_knn_ids(k_indices, search_df)
print(k_ids)

def get_knn_recommendations(k_ids, search_df):
    return search_df.set_index("id").loc[k_ids]

knn_recommendations = get_knn_recommendations(k_ids, search_df)
knn_recommendations

# export results to csv
knn_recommendations.to_csv("recommendations.csv")

def plot_energy_vs_valence(k_indices, metadata_df):

    # plot from entire dataset
    energy = metadata_df["energy"].to_numpy()
    valance = metadata_df["valence"].to_numpy()

    # plot from recommended songs
    energy_r = metadata_df.iloc[k_indices]["energy"].to_numpy()
    valance_r = metadata_df.iloc[k_indices]["valence"].to_numpy()

    fig, ax = plt.subplots()
    # plot energy vs valance for entire dataset
    ax.scatter(valance, energy,s=1)
    # plot e vs v for recommended songs
    ax.scatter(valance_r, energy_r, c="Red", s=10,alpha=0.5)

    ax.set_xlabel("Valence")
    ax.set_ylabel("Energy")
    plt.savefig('energy_vs_valence.png')



    plt.show()

plot_energy_vs_valence(k_indices, metadata_df)

def plot_attributes(k_indices, metadata_df, features):
    # get features used by checking for non-zero weights
    features = [k for k,v in features.items() if v != 0]
    print(features)


    if (len(features) == 2):
        f1 = features[0]
        f2 = features[1]
        # plot from entire dataset
        x = metadata_df[f1].to_numpy()
        y = metadata_df[f2].to_numpy()

        # plot from recommended songs
        x_r = metadata_df.iloc[k_indices][f1].to_numpy()
        y_r = metadata_df.iloc[k_indices][f2].to_numpy()

        fig, ax = plt.subplots()
        # plot x,y for entire dataset
        ax.scatter(x, y,s=1)
        # plot x,y for recommended songs
        ax.scatter(x_r, y_r, c="Red", s=10,alpha=0.5)

        ax.set_xlabel(f"{f1}")
        ax.set_ylabel(f"{f2}")
        plt.savefig('plot_attributes.png')

        plt.show()

    elif (len(features) == 3):


        f1 = features[0]
        f2 = features[1]
        f3 = features[2]
        # plot from entire dataset
        x = metadata_df[f1].to_numpy()
        y = metadata_df[f2].to_numpy()
        z = metadata_df[f3].to_numpy()


        # plot from recommended songs


        x_r = metadata_df.iloc[k_indices][f1].to_numpy()
        y_r = metadata_df.iloc[k_indices][f2].to_numpy()
        z_r = metadata_df.iloc[k_indices][f3].to_numpy()

        fig = plt.figure()
        ax = plt.axes(projection='3d')

        # plot x,y for entire dataset
        #ax.scatter(x, y, z,s=1)
        # plot x,y for recommended songs
        ax.set_xlim(0,1)
        ax.set_ylim(0,1)
        ax.set_zlim(0,1)
        ax.scatter(x_r, y_r,z_r,c="Red", s=10,alpha=0.5)

        ax.set_xlabel(f"{f1}")
        ax.set_ylabel(f"{f2}")
        ax.set_zlabel(f"{f3}")
        fig.tight_layout()
        ax.set_box_aspect(None, zoom=0.85)
        plt.savefig('plot_attributes.png')

        plt.show()

plot_attributes(k_indices, metadata_df, query["features"])



